### ISSUE TITLE
script not generate the traffic light plugin

### ISSUE THREAD

**Issue by kahidna** [kartik468/grafana-generate-pdf-nodejs#1]
hi @kartik468   
thank you for your script, its an awesome tools.
but I found that this script have issue when generate pdf from dashboard which using [traffic light](https://grafana.com/grafana/plugins/snuids-trafficlights-panel/) plugins.
the pdf successfully generated, but its not shown the traffic light. following is the  screenshot of the pdf.
![image](https://user-images.githubusercontent.com/4997301/111751317-edd51900-88c6-11eb-836e-e657524cee1d.png)

and this is the dashboard

![image](https://user-images.githubusercontent.com/4997301/111751582-41dffd80-88c7-11eb-8f71-912a0c0bbe81.png)

I'm not familiar with nodejs, but I figured out that the traffic light is always appear lastly from entire panel on dashboard.
I tried to increase delay time at section `await page.setDefaultNavigationTimeout(120000);` to `await page.setDefaultNavigationTimeout(150000);` but no luck.

is there code that I can add so the pdf can completely generated?

ps:
I use grafana   v7.4.3 (010f20c1c8)
traffic light v1.4.5

**Comment by kartik468** [comment]
@kahidna How long does it take to load these panels? Can u pls try increasing the timeout to like large number lets say 2 to 3mins and see if it is visible in pdf.  If it doesn't get displayed after that too then we will have to debug more.

**Comment by kahidna** [comment]
according to inspect element from firefox browser v86.0.1, using 100Mbps internet connection,
it takes 17 seconds, 
![image](https://user-images.githubusercontent.com/4997301/111931236-5bfb2500-8aed-11eb-9d03-6c76f0e2f114.png)

I tried to increase `await page.setDefaultNavigationTimeout(120000);` to `await page.setDefaultNavigationTimeout(240000);` but the result still same. how can I enable debug mode for your script?

**Comment by kahidna** [comment]
hi @kartik468 is ther update for this issue?

**Comment by kartik468** [comment]
try making headless to false in launch option

**Comment by kahidna** [comment]
hi @kartik468 sorry for late respond. here is the output when I tried using headless false option

![image](https://user-images.githubusercontent.com/4997301/116532115-17dc1b00-a90a-11eb-819c-4fc50deb2ca1.png)


the browser open, and as reported before, the traffic light comes last one.
but I got some error message. here is the error message.
```
Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented
    at /home/alfin/work/grafana-generate-pdf-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/alfin/work/grafana-generate-pdf-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page.pdf (/home/alfin/work/grafana-generate-pdf-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1212:43)
    at /home/alfin/work/grafana-generate-pdf-nodejs/grafana_pdf.js:105:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

any idea?

**Comment by kartik468** [comment]
hi @kahidna i think pdf generation works only when headless is false. i am not really sure why those plugins not displaying.. when i get some time i will check it by creating a dashboard and debug

**Comment by kartik468** [comment]
@kahidna did you find the solution for this? i had checked code for the traffic plugin and i found it uses lots of javascript timers/intervals to update the values. i suspect that might be the issue here

**Comment by kahidna** [comment]
Hi @kartik468  no I haven't found the solution for this issue. As work around I manually do printscreen using printscreen button. Any idea for handle those timer?

I already increase the delay 10 times from your default value but have no luck.

**Comment by kartik468** [comment]
@kahidna This is related to the plugin only and it looks like we can't do anything but update the plugin. so closing the issue.
