### ISSUE TITLE
Script gets stuck

### ISSUE THREAD

**Issue by jguilhermeam** [kartik468/grafana-generate-pdf-nodejs#2]
Hi, i'm trying to execute your script as the original does not get all dashboard in a tall page. However your script doesn't finish execution. Any missing info?

**Comment by kartik468** [comment]
@jguilhermeam have you gone through the example from readme? how you are executing it?

**Comment by jguilhermeam** [comment]
yes @kartik468 i've tried using dockerized puppeteer and manually installed. both get stucked. And if I try to run as root it asks for --no-sandbox mode, but even with that it does not work.

**Comment by kartik468** [comment]
its npm project so you have to install dependencies first. have you done that? if not then follow the steps mentioned in updated readme.

if it still gets stuck then there have to be some error logged. mention that error

**Comment by jguilhermeam** [comment]
i've added the dumpio: true and got this error:

Uncaught TypeError: Cannot read property 'scrollBy' of null", source: __puppeteer_evaluation_script__ (11)

**Comment by kartik468** [comment]
oh.. which version of grafana are you using?

**Comment by jguilhermeam** [comment]
i was using the latest docker image, i think it was 8.1.3

**Comment by kartik468** [comment]
@jguilhermeam ok let me try out with latest version. Just to give you background about the code... code first gets the div which has scrollbar and slowly scrolls it and then take pdf.  meanwhile try to debug by changing the code

**Comment by jguilhermeam** [comment]
ok so i've seen that this line is returning null to 'element' var:

var element = document.querySelector('.view');

so i thought that as this is the element to be scrolled, i've changed it to this:

var element = document.getElementsByClassName('react-grid-layout')[0];

now the script finishes execution and it does generate pdf but still not getting all graphs from my tall dashboard.

**Comment by kartik468** [comment]
@jguilhermeam Hey I have updated the code and tested it with latest grafana-8.1.5. Let me know if it works now

**Comment by jguilhermeam** [comment]
yes it worked! nice! thank you
