### ISSUE TITLE
bars of the "Gauge" cell type are not displayed

### ISSUE THREAD

**Issue by ui67** [kartik468/grafana-generate-pdf-nodejs#7]
The automatic generation of screenshots works smoothly. Thank you for your work. Unfortunately, the bars of the "Gauge" cell type are not displayed. There is an empty field, as seen in the screenshot. Do you have a fix for this? Another question: Is it possible to create a screenshot without the browser bar at the top?

![image](https://github.com/kartik468/grafana-generate-pdf-nodejs/assets/129756112/9f3c6d09-22fe-4266-956a-6e8a3d161ca8)

![image](https://github.com/kartik468/grafana-generate-pdf-nodejs/assets/129756112/f75760eb-92c5-476e-8bdc-e44ccd307b49)

**Comment by ui67** [comment]
Fixed it by adding print_background=True,
and adding &kiosk at the end end of the URL.

**Comment by kartik468** [comment]
where did you add it? please add code snippet so that i will add it in code

**Comment by ui67** [comment]
...    
if (HEADLESS) {
      await page.pdf({
        path: outFile,
        width: VIEWPORT_WIDTH_IN_PX + "px",
        height: height_px + "px",
        //    format: 'Letter', <-- see note above for generating "paper-sized" outputs
        scale: 1,
        displayHeaderFooter: false,
        print_background=True,
        margin: {
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
...


and node grafana_pdf.js "http://localhost:3000/d/YOURLINK&kiosk" admin:admin output/grafana_dash.pdf
